idrac_username: root
idrac_password: 123a123@
networks:
  mgmt:
    vlan: 1234
    network:
      subnet_mask: 255.255.255.0
      default_gateway: 192.168.121.253
dns_servers:
  - 1.2.3.4
  - 5.6.7.8